Repository NaKaLiGoBa/AlgoWithMe-BE, pull requests merged in 2023-10, with the labels that each got.

#10 스키마 작성
  src/main/resources/db/schema.sql
Labels: 💙 BE, 📄 document

#19 chore: 회원가입 로직 수정
  src/main/java/com/nakaligoba/backend/controller/MemberController.java
  src/main/java/com/nakaligoba/backend/entity/Member.java
  src/main/java/com/nakaligoba/backend/service/MemberService.java
  src/test/java/com/nakaligoba/backend/config/JpaConfigTest.java
Labels: 💙 BE, 📦 chore, 🌟 feat

#18 [chore] 스키마 및 엔티티 수정
  src/main/java/com/nakaligoba/backend/entity/AnswerTestcase.java
  src/main/java/com/nakaligoba/backend/entity/AnswerTestcaseInput.java
  src/main/java/com/nakaligoba/backend/entity/Problem.java
  src/main/java/com/nakaligoba/backend/entity/Submission.java
  src/main/java/com/nakaligoba/backend/entity/Submit.java
  src/main/java/com/nakaligoba/backend/entity/Testcase.java
  src/main/java/com/nakaligoba/backend/entity/TestcaseInput.java
  src/main/resources/db/schema.sql
Labels: 💙 BE, 📦 chore

#21 chore: 비밀번호 재설정 로직 수정(#14)
  src/main/java/com/nakaligoba/backend/controller/MemberController.java
  src/main/java/com/nakaligoba/backend/service/MemberService.java
  src/main/java/com/nakaligoba/backend/utils/AuthNumberManager.java
Labels: 💙 BE, 📦 chore, 🌟 feat

#23 [feat] 모든 문제 목록 보기
  src/main/java/com/nakaligoba/backend/controller/ProblemController.java
  src/main/java/com/nakaligoba/backend/controller/dto/CustomPageResponse.java
  src/main/java/com/nakaligoba/backend/controller/dto/ProblemPagingDto.java
  src/main/java/com/nakaligoba/backend/entity/Problem.java
  src/main/java/com/nakaligoba/backend/repository/ProblemRepository.java
  src/main/java/com/nakaligoba/backend/service/ProblemService.java
Labels: 💙 BE, 🌟 feat
