Repository NaKaLiGoBa/AlgoWithMe-BE, pull requests merged in 2023-11, with the labels that each got.

#47 [feat] 풀이 글 수정 기능 추가
  src/main/java/com/nakaligoba/backend/solution/application/SolutionService.java
  src/main/java/com/nakaligoba/backend/solution/controller/SolutionController.java
  src/main/java/com/nakaligoba/backend/solution/controller/dto/SolutionRequest.java
  src/main/java/com/nakaligoba/backend/solution/domain/Solution.java
Labels: 💙 BE, 🌟 feat

#74 [chore] 기존 기능 수정으로 인한 request 및 response 변수 추가(#73)
  src/main/java/com/nakaligoba/backend/controller/payload/response/SolutionResponse.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/SolutionsResponse.java
  src/main/java/com/nakaligoba/backend/domain/SolutionSort.java
Labels: 💙 BE, 📦 chore

#81 [feat] 풀이 글 댓글 리스트 보기 기능 추가(#56)
  src/main/java/com/nakaligoba/backend/controller/CommentController.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/CommentsResponse.java
  src/main/java/com/nakaligoba/backend/domain/CommentSort.java
  src/main/java/com/nakaligoba/backend/repository/CommentLikeRepository.java
  src/main/java/com/nakaligoba/backend/repository/CommentRepository.java
  src/main/java/com/nakaligoba/backend/service/impl/CommentLikeService.java
  src/main/java/com/nakaligoba/backend/service/impl/CommentService.java
Labels: 💙 BE, 🌟 feat

#82 [feat] 답글 작성
  src/main/java/com/nakaligoba/backend/controller/ReplyController.java
  src/main/java/com/nakaligoba/backend/controller/payload/request/ReplyRequest.java
  src/main/java/com/nakaligoba/backend/domain/Reply.java
  src/main/java/com/nakaligoba/backend/repository/ReplyRepository.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyService.java
Labels: 💙 BE, 🌟 feat

#84 [feat] 풀이 글에 대한 댓글 삭제 기능(#83)
  src/main/java/com/nakaligoba/backend/controller/CommentController.java
  src/main/java/com/nakaligoba/backend/repository/CommentLikeRepository.java
  src/main/java/com/nakaligoba/backend/repository/ReplyLikeRepository.java
  src/main/java/com/nakaligoba/backend/repository/ReplyRepository.java
  src/main/java/com/nakaligoba/backend/service/impl/CommentLikeService.java
  src/main/java/com/nakaligoba/backend/service/impl/CommentService.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyLikeService.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyService.java
Labels: 💙 BE, 🌟 feat

#87 fix: 권한 관련 예외 수정
  src/main/java/com/nakaligoba/backend/exception/UnauthorizedAccessException.java
  src/main/java/com/nakaligoba/backend/global/GlobalExceptionHandler.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyService.java
Labels: 💙 BE, 🐞 fix

#89 [feat] 풀이 글 리스트 보기 수정
  src/main/java/com/nakaligoba/backend/controller/SolutionController.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/SolutionsResponse.java
  src/main/java/com/nakaligoba/backend/repository/SolutionRepository.java
  src/main/java/com/nakaligoba/backend/service/impl/SolutionService.java
Labels: 💙 BE, 🌟 feat

#90 [fix] 문제 조회 시 채점용 테스트케이스 응답에서 제거
  src/main/java/com/nakaligoba/backend/service/impl/ProblemService.java
  src/test/java/com/nakaligoba/backend/service/impl/ProblemServiceTest.java
Labels: 💙 BE, 🐞 fix

#95 [feat]답글 좋아요, 조회, 삭제 기능 추가
  src/main/java/com/nakaligoba/backend/controller/ReplyController.java
  src/main/java/com/nakaligoba/backend/controller/payload/request/ReplyLikeRequest.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/RepliesResponse.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/ReplyLikeResponse.java
  src/main/java/com/nakaligoba/backend/domain/Member.java
  src/main/java/com/nakaligoba/backend/domain/ReplyLike.java
  src/main/java/com/nakaligoba/backend/domain/Solution.java
  src/main/java/com/nakaligoba/backend/repository/ReplyLikeRepository.java
  src/main/java/com/nakaligoba/backend/repository/ReplyRepository.java
  src/main/java/com/nakaligoba/backend/service/dto/ReplyDto.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyLikeService.java
  src/main/java/com/nakaligoba/backend/service/impl/ReplyService.java
  src/main/resources/db/schema.sql
Labels: 💙 BE, 🌟 feat

#113 [test] 회원관련 및 풀이 댓글 관련 테스트코드 추가(#112)
  src/test/java/com/nakaligoba/backend/service/impl/AuthServiceTest.java
  src/test/java/com/nakaligoba/backend/service/impl/CommentServiceTest.java
Labels: 💙 BE, 🪞 test

#115 [test] 풀이글 및 답글 관련 테스트코드 추가
  src/test/java/com/nakaligoba/backend/service/impl/ReplyServiceTest.java
  src/test/java/com/nakaligoba/backend/service/impl/SolutionServiceTest.java
Labels: 💙 BE, 🪞 test

#126 [chore] RestTemplate 내 https 프록시 설정 추가
  build.gradle
  src/main/java/com/nakaligoba/backend/service/component/KakaoWebClient.java
Labels: 💙 BE, 📦 chore

#127 chore: RestTemplate 내 https 프록시 설정 추가
  build.gradle
  src/main/java/com/nakaligoba/backend/service/component/KakaoWebClient.java
Labels: 💙 BE, 📦 chore, 🧱 devops

#146 [feat] 풀이 글 목록 보기 내 작성된 언어 목록 추가
  src/main/java/com/nakaligoba/backend/controller/payload/response/SolutionsResponse.java
  src/main/java/com/nakaligoba/backend/service/impl/SolutionService.java
Labels: 💙 BE, 🌟 feat

#149 [feat] 문제 조회 시 제출 기록 개수 조회 및 jwt 만료시간, 유효성 체크
  src/main/java/com/nakaligoba/backend/controller/ProblemController.java
  src/main/java/com/nakaligoba/backend/controller/SubmitController.java
  src/main/java/com/nakaligoba/backend/controller/payload/response/ProblemResponse.java
  src/main/java/com/nakaligoba/backend/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/nakaligoba/backend/filter/JwtAuthorizationFilter.java
  src/main/java/com/nakaligoba/backend/repository/SubmitRepository.java
  src/main/java/com/nakaligoba/backend/service/impl/ProblemService.java
  src/main/java/com/nakaligoba/backend/utils/JwtUtils.java
  src/test/java/com/nakaligoba/backend/service/impl/ProblemServiceTest.java
Labels: 💙 BE, 🌟 feat
